### ISSUE TITLE
As an employer, I want to show some texts written by my company highlighting why it is beneficial for the employee to join my organisation.

### ISSUE THREAD

**Issue by ahhnsys** [Utkarsh-Marwaha/XeroDiscrimination#10]

**Comment by KarmickLiu** [comment]
Acceptance Criteria:

There is a description section on the employer profile page that displays texts/images/videos of the employer's company.
There is an input box on the employer profile edit page that employers could upload texts/images/videos to the above pages.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
