### ISSUE TITLE
As a client, I want to display some positive feedback in the form of short paragraph/video/images for our website.

### ISSUE THREAD

**Issue by raymondluozq** [Utkarsh-Marwaha/XeroDiscrimination#17]

**Comment by KarmickLiu** [comment]
Acceptance criteria:

There is a description section on the employer profile page that displays texts/images/videos of the employer's company.
There is an input box on the employer profile edit page that could upload texts/images/videos to the employer profile page.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
