### ISSUE TITLE
As an employer, I want to show the logo, the name and the service type of my company.

### ISSUE THREAD

**Issue by ahhnsys** [Utkarsh-Marwaha/XeroDiscrimination#3]
The logo and name of employer's company should be obvious and easy to find.

**Comment by KarmickLiu** [comment]
Acceptance Criteria:

There is a title section on the employer profile page that displays the logo, the name and the service type of the employer's company.
There is an input box on the employer profile edit page that employers could upload their company's basic information such as name, logo, type to the employer profile page.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
