### ISSUE TITLE
As an employer, I want to be able show the location of the company headquarters

### ISSUE THREAD

**Issue by ahhnsys** [Utkarsh-Marwaha/XeroDiscrimination#4]
While some bigger companies have multinational operations, jobs provided by smaller companies are restricted to their singular jurisdiction.

**Comment by KarmickLiu** [comment]
Acceptance Criteria:

There is a map section on the employer profile page that displays the map location and the name of the location of the employer's company headquarters.
There is an input box on the employer profile edit page that employers could select their location on the map and update the location to the employer profile page.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
