### ISSUE TITLE
As a client, I want to have special badges only for 'Rainbow Ticked' accredited organisations, so that community can spot them easier.

### ISSUE THREAD

**Issue by KarmickLiu** [Utkarsh-Marwaha/XeroDiscrimination#41]
Important feature:)

**Comment by KarmickLiu** [comment]
Acceptance criteria:

There is a Rainbow Tick badge displayed after Rainbow Tick accredited organisations' names on the employer page.
There is a Rainbow Tick badge displayed after jobs' names on job-related pages if the job is offered by a Rainbow Ticked organisation.
There is a Rainbow Tick page to where you will be redirected when you click on the Rainbow Tick badge on any page.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
