### ISSUE TITLE
As an employer, I want to be able to show the contact details of my company

### ISSUE THREAD

**Issue by ahhnsys** [Utkarsh-Marwaha/XeroDiscrimination#6]
Mainly the website address, an email or phone number

**Comment by KarmickLiu** [comment]
Acceptance Criteria:

There is a contact section on the employer profile page that displays the contact details of the employer.
There is an input box on the employer profile edit page that employers could upload their contact details to the employer profile page.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
