### ISSUE TITLE
As an employer, I want to be able to show a list of all jobs advertised by my company

### ISSUE THREAD

**Issue by ahhnsys** [Utkarsh-Marwaha/XeroDiscrimination#7]

**Comment by KarmickLiu** [comment]
Acceptance Criteria:

There is a job list section on the employer profile page that displays available jobs of the employer's company.
There is an input box on the employer profile edit page that employers could upload jobs to the employer profile page.

**Comment by shreyasn995** [comment]
Reviewed by Xero.
